### ISSUE TITLE
Too many black question marks

### ISSUE THREAD

**Issue by Openskiy** [procommerce-io/procurrency#10]
After I installed ProCurrency desktop wallet v1.3.5.1-REV2 I started getting a lot of black question marks. I think even some of the previously green checkmarks turned to black question marks.
What can be done?
Thanks

**Comment by rkanadev** [comment]
The black question marks mean everything you have staked on the wrong chain is now rejected by the main chain therefore your mined block are now orphaned. Just leave your running as usually and you will start to stake again as you have updated to v1.3.5.1-REV2, you are on the right chain (main chain).
Always update your wallet when there is a release.

Thanks!

**Comment by Openskiy** [comment]
Still not staking.

**Comment by rkanadev** [comment]
How many coins have you in your wallet? Backup your "wallet.dat", delete everything in your ProCurrency "roaming folder" and resync your wallet from scratch with the latest version (v1.3.5.1-REV2) of course.

**Comment by Openskiy** [comment]
I am staking now. Thanks, 

----- Original Message -----

**Comment by rkanadev** [comment]
Ok. Please close the issue if everything is resolved. Thanks!

**Comment by Openskiy** [comment]
I am getting notifications when rewards come in but they never show up in the transaction history. 

Any ideas? 
Screen shot of my version: 


Thanks, 

Michael 
----- Original Message -----

**Comment by rkanadev** [comment]
where is the screenshot?

**Comment by PROC-Patriarch** [comment]
This will help.

Please head over to Help>Debug Window>Console

Type this command:

clearwallettransactions

Press enter.
Now exit the wallet and re-open it after 5 seconds or so.

Head over to the Console and type this command;

scanforalltxns 150000

Press enter and wait till you get a response.
This will rescan all your transactions and keep a fresh log

**Comment by rkanadev** [comment]
issue closed
