### ISSUE TITLE
1.3.5.2 rev3 stuck on block 398273?

### ISSUE THREAD

**Issue by CharlyBarley** [procommerce-io/procurrency#11]
hi, i recently updated on linux to 1.3.5.2 rev3, and i seem to be stuck on block 398273 for the past 17 hours with 8 transactions stuck  in the confirmation phase.  can you recommend a fix please? thank you

**Comment by rkanadev** [comment]
hi, did you update it from which version? Please close and relaunch the wallet and let me know if that fix the issue.
thanks!

**Comment by CharlyBarley** [comment]
hi, i updated from rev 2, and rev 3 worked good for a few weeks. it started moving forward again since i opened the issue, but then it seemed to get stuck on block 399969 for a day now. not sure what is going on. i keep cleaning up the failed transactions from the consol, using clearalltransactions and then scanforalltxns 1, and i periodically restart the qt to try to get it working better. one thing i notice is that i have had fewer connections than usual. around 2-4, whereas i was getting 9-14 before, even up to 22 sometimes.thanks

**Comment by rkanadev** [comment]
ok just leave it running. There is a new update coming in about a week. The connections and everything else will comeback to normal in the next future versions. Please keep your wallet updated to the latest version always.
Thanks!

**Comment by CharlyBarley** [comment]
ok thanks, it finally synced up. i think works best when i wait until it syncs up before i unlock for staking, all of a sudden a bunch of confirmed mines came in today. there is probably not too many using linux on this, thanks again

**Comment by CharlyBarley** [comment]
Hi, my wallet was just not syncing up so i reset the block by clearing out the procurrency folder except for the dat file. i got it to sync finally but i lost 3000 proc, all the confirmed mines from the past few months, so i replaced the dat file with a recent file from july 7, but still no change and i typed scanforalltxns 1 in the console but still nothing. is there something i can type in the console to find those confirmed mines or are they lost? thanks

**Comment by CharlyBarley** [comment]
Hi, my wallet was just not syncing up so i reset the block by clearing out the procurrency folder except for the dat file. i got it to sync finally but i lost 3000 proc, all the confirmed mines from the past few months, so i replaced the dat file with a recent file from july 7, but still no change and i typed scanforalltxns 1000 and scanforalltxns 1 in the console but still nothing. is there something i can type in the console to find those confirmed mines or are they lost? i only have one mining transaction that came back from 5/21/18.... thanks

**Comment by rkanadev** [comment]
did you make a manual backup before syncing from scratch?
Please use this command when launching your procurrency wallet:
Launch the terminal and cd into your ProCurrency Folder and type:
./ProCurrency-Qt -rescan

Or use the cammand -rescan with the way you launch your ProCurrency Wallet.
thanks!

**Comment by CharlyBarley** [comment]
yes i used the most recent wallet.dat in the procurrency folder first, i deleted all files and folders except for that most recent dat file. i tryed that and the mines didn't show up, so then i tryed the manual backup (switched and replaced the dat file) from a few days earlier and still no difference. i apologize i'm have trouble understanding how to use this rescan command. i tryed it in the debugging console inside the wallet and it didn't recognize it, and then i tryed it inside a linux terminal opened up inside the .procurrency directory and it said no such directory, but was already inside the procurrency directory so i tryed the -rescan and it still didn't recognize it. do i need to have the wallet open when i try this command  in the linux terminal inside the .procurrency directory? i tryed that, thanks

**Comment by CharlyBarley** [comment]
thanks, i did this, but the 3000 extra mines that i thought i had still disappeared. i guess they were accepted mining errors? funny thing is i got 3x more proc now since ipn urged us to get all our commissions out of our back office and gave us proc as an option for payout.  i'm not getting very frequent mines or stakes though. about one every few days and occasionally 2 on the same day. i was getting about 100proc a day before, but i guess it was all errors...dang...not really worth mining unless you got millions of proc at stake....several hundred thousand proc at stake won't get you many mines....

**Comment by PROC-Patriarch** [comment]
Please head over to Help>Debug Window>Console

Type this command:

clearwallettransactions

Press enter.
Now exit the wallet and re-open it after 5 seconds.

Head over to the Console and type this command;

scanforalltxns 150000

Press enter and wait till you get a response.
This will rescan your transactions from block 150k

**Comment by CharlyBarley** [comment]
thanks
