### ISSUE TITLE
PROC v1.3.6 BR qt executable won't open up wallet

### ISSUE THREAD

**Issue by CharlyBarley** [procommerce-io/procurrency#12]
hello, on my same ubuntu 14 distro, i deleted the old qt executable and old version download, and then downloaded the new version PROC v1.3.6 BR, unzipped and clicked on the new qt executable and it won't open up the wallet. i didn't do anything to my .procurrency folder. thanks

**Comment by CharlyBarley** [comment]
hi again, i redownloaded the previous version and open that qt file and the wallet launched fine and is syncing. can you list all the linux terminal commands to update and launch the new qt executable and all updates needed to make that qt work, thanks.

**Comment by rkanadev** [comment]
You need to have secp256k1 built and installed on your linux system before
launching v1.3.6.
Please clone the repo and do
cd procurrency/src/secp256k1
then
Follow the Instructions on how to build and make install:

Install Autoreconf first
sudo apt-get install dh-autoreconf

then

libsecp256k1 is built using autotools:

$ ./autogen.sh
$ ./configure --enable-module-recovery
$ make
$ sudo make install

After secp256k1 is built and installed, then you can launch your
ProCurrency-qt for linux.

I will embed secp256k1 into Future procurrency wallet linux releases so
that there will be no need to install it first.

**Comment by rkanadev** [comment]
Hi, have you been able to fix your issue?

**Comment by CharlyBarley** [comment]
not yet, i'm still working on this today, i let you know if i get it going again.  thank you for your help

**Comment by rkanadev** [comment]
Closing this issue.
