### ISSUE TITLE
Install PROC Wallet on  ubuntu server 16.04

### ISSUE THREAD

**Issue by atomlab** [procommerce-io/procurrency#17]
Hi. I don't understand how to install proc wallet  on ubuntu server 16.04 and sync blockchain ? I want use RPC for work with wallet. Can you give link to documentation for this case ?

**Comment by rkanadev** [comment]
Hi, here is a quick way to build ProCurrency daemon (procd) on ubuntu 16.04
1:
sudo apt-get update
2:
sudo apt-get upgrade
3:
sudo apt-get install build-essential libssl-dev libboost-all-dev git libdb++-dev libminiupnpc-dev screen

And then you git clone procurrency source code:
git clone https://github.com/procommerce-io/procurrency

You Install Autoreconf:
sudo apt-get install dh-autoreconf

And then:
4) cd procurrency/src
5) make -f makefile.unix
6) strip procd

From there you are good to go. If you run into issues, do:
cd procurrency/src
make clean -f makefile.unix

and

cd procurrency/src/leveldb
chmod +x build_detect_platform
