### ISSUE TITLE
windows wallet block stuck at 499100

### ISSUE THREAD

**Issue by thom64** [procommerce-io/procurrency#19]
I recently found that i couldn't sync my wallet beacuse it was stuck on block 497100. 
after checking updating to the most recent wallet and the problem not resolving, i tried the fix sugessted in this video.

it fixed my syncing issue, but i lost all the coins i had mined.

i have backed up both versions of the files, so i can go back, but i cant figure out how to get my wallet synced and all my coins.

please help

**Comment by thom64** [comment]
correction: block no. is 499100

**Comment by rkanadev** [comment]
First Backup your original wallet.dat (the one with all your coins) then delete everything from ProCurrency Folder in "roaming" except the "Backups" Folder.
Launch v1.3.8 and sync from scratch. v1.3.8 will create a new "empty wallet.dat" just wait until the blockchain is fully synced then close v1.3.8 Windows - delete or rename that newly created "empty wallet.dat" and replace it with your Original wallet.dat with coins.
Relaunch v1.3.8 and let do its work - it will bring back all coins on the current blockchain.

**Comment by thom64** [comment]
unfortunately this only reaped the same result as my previous recovery efforts. still missing all mined coins

**Comment by rkanadev** [comment]
"still missing all minded coins"?
what ProCurrency version did you update your wallet from?
Try -rescan when launching v1.3.8

**Comment by PROC-Patriarch** [comment]
You need to clear your LOG and RESCAN
Please head over to Help>Debug Window>Console

Type this command:

clearwallettransactions

Press enter.
Now exit the wallet and re-open.

Head over to the Console and type this command;

scanforalltxns 150000

Press enter and wait till you get a response.
This will rescan all your transactions from block 150k
If you have older transactions simple do this code

scanforalltxns 15000

It may take up to 30 minutes scanning.

Thank you!
