### ISSUE TITLE
blkindex.dat

### ISSUE THREAD

**Issue by godfather288** [procommerce-io/procurrency#20]
I tried to open up my Prowallet and keep getting this BLKindex.dat error message. any help would be great.

![untitled](https://user-images.githubusercontent.com/36119672/52718808-49a77800-2f72-11e9-818d-f60d5ca1c73f.png)

**Comment by rkanadev** [comment]
This error means, your Blockchain is corrupted. Please backup your wallet.dat, delete everything and resync ProCurrency from scratch. After it is fully synced, replace the newly created wallet.dat with your Backup wallet.dat with funds. Everything should comeback to normal.

**Comment by godfather288** [comment]
so i deleted everything and used my backup wallet and its only showing that i have 65000tokens but in my transaction log i see where i should have over 900k tokens. the back up needs to be fixed???
________________________________

**Comment by PROC-Patriarch** [comment]
It needs to sync fully for the coins to show up

**Comment by rkanadev** [comment]
have you been able to get your wallet fully working?
