### ISSUE TITLE
sync issue

### ISSUE THREAD

**Issue by Troni307** [procommerce-io/procurrency#21]
Wallet seems to be synced but continues to say out of sync. I know there is more blocks that its showing. I have synced 545391. i know there's up to 551000.
version 1.3.8 BR

I first got the wallet in December because my rewards were going to expire and needed to transfer out. So i did before it was synced. Should I be receiving those before its synced up? My transaction was successful and I know what block its included in which I'm synced up long past. but it doesnt show in my wallet.
Ive been syncing for over 2 months now. repeatedly done rewind, close and open. never re-install tho.
Wallet QT

**Comment by PROC-Patriarch** [comment]
Hello,

What operating system are you using?

**Comment by Troni307** [comment]
Windows 7

**Comment by rkanadev** [comment]
Please update to latest release and close this issue if everything is working well.

**Comment by Troni307** [comment]
i had to delete the files and then it synced up.
