### ISSUE TITLE
Sync problem on my Mac

### ISSUE THREAD

**Issue by Humingbear** [procommerce-io/procurrency#22]
Wallet seems to be synced but continues to say out of sync. I know there is more blocks that its showing. I have synced 525599. i know there's up to 556311.
version 1.3.5.2: Rev3

I've been trying to syncing every day...it keeps saying last block generated 75 days ago...It looks like it is loading and then it reverts back.  I've had it get to only 837 blocks remaining and then it resets back.  I want to install the current updated wallet.  Suggestions please

**Comment by rkanadev** [comment]
Please update to the latest version: ProCurrency v1.39.0
https://github.com/procommerce-io/procurrency/releases
v1.39.0 MacOSX wallet has been released and available for download.
Just launch the latest version and the syncing should resume.
Thanks!

**Comment by rkanadev** [comment]
Did you successfully update your wallet to the latest release?

**Comment by rkanadev** [comment]
Closing this issue
