### ISSUE TITLE
I did the latest update v1.39.0 and now after about an hour it says no active connection and stuck at 582592

### ISSUE THREAD

**Issue by Reneeo2** [procommerce-io/procurrency#24]

**Comment by rkanadev** [comment]
Restart your wallet and check your firewall if it is not block ProCurrency connections. 
What OS are you using?

**Comment by Reneeo2** [comment]
I am using Mac and it is working now.  Thanks  

Renee

**Comment by rkanadev** [comment]
Ok please close this issue if everything is working. Thanks!

**Comment by Reneeo2** [comment]
Hi it is off line again.  I did check my firewall and it is not on to block procurrency.  What is the best way to restart my wallet?  It seems i have trouble often when my computer is shut off and i restart.

Renee
