### ISSUE TITLE
Wallet gets stuck syching. Many orphan blocks.

### ISSUE THREAD

**Issue by cryptalt** [procommerce-io/procurrency#5]
Please provide a bootstrap. I can't keep wallet in sync with chain. Multiple tries from fresh start get stuck processing chain.

**Comment by rkanadev** [comment]
The wallet has no sync issue. Check your computer time, close everything and launch ProCurrency-Qt wallet from fresh start and leave it. Normally the syncing takes around 3-3hrs depending on your computer performance.

**Comment by cryptalt** [comment]
In my own experience, it took several days to get it to sync. The wallet would get stuck on orphaned blocks for about 8 hour stretches. Don't take my word for it, try synching from scratch yourself. It's bad.

**Comment by rkanadev** [comment]
Everything is well tested before each release. I sync every latest version from scratch before releasing anything on github. Can you attach your debug file here and i will take a look.

**Comment by rkanadev** [comment]
This issue is now closed. Syncing has no problem.
