### ISSUE TITLE
how to update on Linux 14.04 64bit to PROC v1.3.5?

### ISSUE THREAD

**Issue by CharlyBarley** [procommerce-io/procurrency#6]
Hi, can someone please show me the commands to update pro wallet for Linux 14.04 64bit to PROC v1.3.5 , my wallet shows i'm using ProCurrency v1.1.0.0: Initial thank you

i downloaded the tar.gz zip file for PROC v1.3.5 to my desktop, when i go to unzip it ProCurrency-qt, linux tells me there is already a file named ProCurrency-qt, and it asked if i want to replace it. if i answer yes, will it upgrade the software? can someone please show me the process to update, thank you

**Comment by rkanadev** [comment]
Please delete v1.3.5 that you downloaded and redownload v1.3.4.1 - we reverted everything back to that version. when you do, you need to first close v1.1.0.0 and then delete or backup v1.1.0.0 ProCurrency-qt Linux and then Unzip v1.3.4.1 and start ProCurrency-qt again.

let me know if you have any other issue. thanks!

**Comment by CharlyBarley** [comment]
thanks, so while unzipping v1.3.4.1 answer yes to replacing the previous qt excutable? i have been unable to find the directory for the wallet in the event that i need to use the back up file? how do i find this in linux terminal and replace the .dat with a backup? if i save a backup .dat file is it usable to recover on any OS? thank you

**Comment by rkanadev** [comment]
are you on unbuntu 14 desktop or server? For the Procurrency-qt linux binary replacement update, you can answer yes. But for future updates, please know where your unzip files are going. If you are using ubuntu 14 desktop, you need to go to Home directory to see all your folders and files. While in the Home directory, click on "View" and then select "Show hidden files" or something similar. You will see a .procurrency folder. You really dont need to manually backup you wallet.dat as it automatically backup itself when you relaunch Procurrency-qt in the folder "backups"

**Comment by CharlyBarley** [comment]
got it to work, thank you very much, appears to be syncing and my addresses showed up, cool... do you think it is even worth my time and energy trying to stake with 80k proc? people got like ridiculous amounts of proc and are getting all the stakes? linux is much more efficient when compared to windows...i was messing around with this before and have several receive addresses. one of the addresses showed up at the ME icon in the upper right corner, should i use this address to send proc from ipro?  probably doesn't matter what address as long as it is one on my receive list? thank you again

**Comment by rkanadev** [comment]
Im glad to got it worked. It doesnt matter which address you will use to receive any transfer as long as the receive addresses belong to your wallet.

Thanks!
