### ISSUE TITLE
Procurrency wallet recommended settings for linux

### ISSUE THREAD

**Issue by CharlyBarley** [procommerce-io/procurrency#7]
hi, i've left my laptop staking on, staking enabled, unlocked, and synced for several days now staking with 77700 proc, and yet i don't see any staking results yet, and keeps saying estimated 2 days for rewards.  is this enough coins  at stake to do any good? and what settings do you recommend in options for staking as far as interval, ring size, etc... here is a screen shot at what i have the wallet settings set on, thanks
![screenshot - 05082018 - 01 38 15 pm](https://user-images.githubusercontent.com/29241639/39776295-0b1a826e-52c6-11e8-8112-024cccb9c99c.png)

**Comment by rkanadev** [comment]
Your settings are correct but your Total amount of PROC is very low to regular Stake. You will still stake with that amount of coins but it will take you few days to a week as the POS difficulty is now high. Just leave your wallet an forget abt it. The 2 days estimation is just an estimation; all depend on your actual Staking weigh to find a block which can happen anytime but in your case, you need to patient and keep your wallet running 24hrs as long as you can.
Thanks

**Comment by CharlyBarley** [comment]
thanks
