### ISSUE TITLE
Procurrency wallet not staking all available matured coins?

### ISSUE THREAD

**Issue by kawika357** [procommerce-io/procurrency#8]
Hello,
I have an issue with my wallet and it properly staking coins.  I have 100995 coins that I assumed all were being staked but when I finally got my second mining reward it then told me only 35014.99 were staked and the rest were still spendable? The estimated time to earn reward was 1-2 days the whole time I had my wallet open (I know it's only an approximation) but it took 6 days to get my last reward.  My wallet had said the full 100995 coins were staking the entire time too.  Here is a screenshot of my wallet...seems to me when I transferred 34199.99 PROC from the exchange to my wallet on 5/5 plus my first mining reward is how the wallet is staking 35014.99?  

![image](https://user-images.githubusercontent.com/39277937/40073820-ce9d599e-582c-11e8-9395-6ef2be50f42a.png)

I went to the debug window and typed getstakinginfo and it said this:

  | {"enabled" : true,"staking" : false,"errors" : "","currentblocksize" : 1000,"currentblocktx" : 0,"pooledtx" : 0,"difficulty" : 44798550.53132159,"search-interval" : 16,"weight" : 0,"netstakeweight" : 35858724365247628,"expectedtime" : 0}
-- | --

If my staking is false then is there something wrong with the way my wallet is configured?  I made sure staking was enabled in the options box so I am not sure why all of my coins aren't staking?  Maybe it has something to do with the wallet being rolled back?  My wallet has been open and unlocked the entire time so I am not sure what the issue is.  Sorry for the lengthy post but I really appreciate any help you can give me!

**Comment by rkanadev** [comment]
First please update your wallet to the latest version v1.3.5-RC2 as there are two Mandatory Forks coming.
There is nothing wrong with your staking, just leave your wallet running - it is normal the way your staking is working. Nothing wrong.

Thank you.
