### ISSUE TITLE
roll back blocks with linux update?

### ISSUE THREAD

**Issue by CharlyBarley** [procommerce-io/procurrency#9]
hello, some of the instructions for updating on other operating systems i saw said they had to roll back the blocks 1000 or something? is this necessary on the linux version? i deleted all the old wallet files and folders and opened the latest qt file updated version and then dropped my saved wallet.dat file back in the new procurrency file and it synced up.  i should be okay right? after about 12 days  i got 2 staking transactions and they both say generated but not accepted mined, does this mean someone else got them, or does it mean they just haven't matured yet? thank you

**Comment by rkanadev** [comment]
It is not necessary if your latest Block Height is the same as the Official Block Explorer: https://procsight.com/
The staking is little bit tricky, when it says "mined but not accepted" that means someone else staked the same block like you and you both staked it few seconds apart or something. The person who got it first get it accepted and the second person block get invalidated by the network.

Please check your Block Height at: https://procsight.com/

Thank you.

**Comment by rkanadev** [comment]
Please always remember to close your "Opened Issue" if you are satisfy with the response given.
Thanks!
